---
# tasks file for roles/app-database
- name: Create DATABASE container
  community.docker.docker_container:
    name: database
    image: maximedubois1cpe/database:latest
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - name: app-network
    env_file: /home/centos/.env
