---
# tasks file for roles/proxy
- name: Creatde FRONT container
  community.docker.docker_container:
    name: httpd
    image: maximedubois1cpe/proxy:latest
    networks:
      - name: app-network
    ports:
      - 80:80