---
# tasks file for roles/app-back
- name: Create BACK container
  community.docker.docker_container:
    name: back
    image: maximedubois1cpe/tp-devops-simple-api:latest
    networks:
      - name: app-network
    env_file: /tmp/.env
    ports:
      - "8080:8080"
    recreate: true
    pull: true