- hosts: all
  gather_facts: false
  become: true
  vars: 
    ansible_user: "centos"

  roles:
    #- roles/docker
    #- roles/network
    - env
    - app-database
    - app-back
    - app-front
    - proxy

