version: '3.8'

services:
    back:
        container_name: back
        build: BackendAPI/simple-api-student
        networks:
          - my-network
        depends_on:
          - database
        env_file:
          - .env
  
    database:
        container_name: database
        build: database
        networks:
          - my-network
        env_file:
          - .env
        volumes:
          - data:/var/lib/postgresql/data

    httpd:
        container_name: proxy
        build: Front
        ports:
          - 80:80
          - 8080:8080
        networks:
          - my-network
        depends_on:
          - back

    www:
        container_name: www
        build: Front/devops-front-main
        networks:
          - my-network
        depends_on:
          - back

networks:
    my-network:

volumes:
    data: