name: Deploy with Ansible to aws
on:
  workflow_run:
    workflows: ["Build push"]
    types: [completed]
    branches:
      - 'main'

jobs:
  ansible-deploy:
    runs-on: ubuntu-22.04
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Run deploy playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
        # Required, playbook filepath
          playbook: playbook.yml
          # Optional, directory where playbooks live
          directory: ./ansible
          # Optional, ansible configuration file content (ansible.cfg)
          configuration: |
            [defaults]
            ansible_user=centos
          # Optional, SSH private key
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Optional, literal inventory file contents
          # inventory: |
          #   [all]
          #   damien.mailhebiau.takima.cloud
          inventory: ${{ secrets.ANSIBLE_INVENTORY }}