name: Build push
on:
    workflow_run:
        workflows: ["CI devops 2023"]
        types:
            - completed            
jobs:
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    env:
      backdir: ./TP/Part_01/BackendAPI/simple-api-student
      databasedir: ./TP/Part_01/database
      frontdir: ./TP/Part_01/Front
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name : Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ${{env.backdir}}
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ${{env.databasedir}}
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ${{env.frontdir}}
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}
