name: Build push
on:
  workflow_run:
    workflows: ["CI devops 2023"]
    types:
        - completed   
jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    env:
      backdir: ./TP/Part_01/BackendAPI/simple-api-student
      databasedir: ./TP/Part_01/database
      httpddir: ./TP/Part_01/Front
      frontdir: ./TP/Part_01/Front/devops-front-main
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name : Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ${{env.backdir}}
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ${{env.databasedir}}
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ${{env.httpddir}}
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/proxy:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push front
        uses: docker/build-push-action@v3
        with:
          context: ${{env.frontdir}}
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/frontend:latest
          push: ${{ github.ref == 'refs/heads/main' }}